# Generated by Django 3.1.7 on 2021-03-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210312_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_color', models.CharField(max_length=120)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cus', to='myapp.customer')),
            ],
        ),
    ]
